### ISSUE TITLE
RuboCop LSP fails with custom gems

### ISSUE THREAD

**Issue by kylesnowschwartz** [williamboman/mason.nvim#1919]
### I've searched open issues for similar requests

- [x] Yes

### I've manually reviewed logs to find potential errors

- [x] Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [x] Yes

### Problem description

When using the RuboCop LSP with custom gems (e.g., custom RuboCop extensions), the LSP fails because Mason's isolated RuboCop installation can't find these gems.

The RuboCop LSP crashes with errors like:
`cannot load such file -- rubocop-marketplace`

### Expected behavior

  The RuboCop LSP should either:
  1. Have access to project-specific gems
  2. Gracefully handle missing gems
  3. Provide a way to specify additional gem paths

  ### Workaround
  I've created a workaround by symlinking my custom gem into Mason's RuboCop gem path:
```
  #!/usr/bin/env bash
  # This script sets up Mason's RuboCop installation to work with custom RuboCop gems

  set -e

  # Set paths - customize these to your environment
  MASON_RUBOCOP_PATH="$HOME/.local/share/nvim/mason/packages/rubocop"
  PROJECT_ROOT=$(pwd)
  CUSTOM_GEM_NAME="rubocop-custom"  # Replace with your custom gem name
  CUSTOM_GEM_VERSION="1.0.0"        # Replace with your custom gem version
  CUSTOM_GEM_PATH="$PROJECT_ROOT/gems/$CUSTOM_GEM_NAME"  # Adjust path as needed

  echo "Setting up custom RuboCop gem for Mason's RuboCop..."
  echo "Mason RuboCop path: $MASON_RUBOCOP_PATH"
  echo "Custom gem path: $CUSTOM_GEM_PATH"

  # Check if Mason's RuboCop is installed
  if [ ! -d "$MASON_RUBOCOP_PATH" ]; then
    echo "Error: Mason RuboCop not found at $MASON_RUBOCOP_PATH"
    echo "Please install RuboCop LSP through Mason first"
    exit 1
  fi

  # Check if custom gem exists
  if [ ! -d "$CUSTOM_GEM_PATH" ]; then
    echo "Error: Custom gem not found at $CUSTOM_GEM_PATH"
    echo "Please ensure the gem exists and path is correct"
    exit 1
  fi

  # Create symbolic links for the gem in Mason's gem paths
  echo "Creating directories and symlinks..."
  mkdir -p "$MASON_RUBOCOP_PATH/gems/$CUSTOM_GEM_NAME-$CUSTOM_GEM_VERSION/lib"
  ln -sf "$CUSTOM_GEM_PATH/lib/rubocop" "$MASON_RUBOCOP_PATH/gems/$CUSTOM_GEM_NAME-$CUSTOM_GEM_VERSION/lib/"

  # Create a simple gemspec file in the Mason gem directory
  echo "Creating gemspec file..."
  cat > "$MASON_RUBOCOP_PATH/gems/$CUSTOM_GEM_NAME-$CUSTOM_GEM_VERSION/$CUSTOM_GEM_NAME.gemspec" << EOF
  Gem::Specification.new do |s|
    s.name = '$CUSTOM_GEM_NAME'
    s.version = '$CUSTOM_GEM_VERSION'
    s.summary = 'Custom RuboCop rules'
    s.authors = ['Developer']
    s.files = Dir['lib/**/*']
    s.require_paths = ['lib']
  end
  EOF

  # Create the specification file so RuboCop can find the gem
  echo "Creating gem specification..."
  mkdir -p "$MASON_RUBOCOP_PATH/specifications"
  cat > "$MASON_RUBOCOP_PATH/specifications/$CUSTOM_GEM_NAME-$CUSTOM_GEM_VERSION.gemspec" << EOF
  # -*- encoding: utf-8 -*-
  # stub: $CUSTOM_GEM_NAME $CUSTOM_GEM_VERSION ruby lib

  Gem::Specification.new do |s|
    s.name = "$CUSTOM_GEM_NAME".freeze
    s.version = "$CUSTOM_GEM_VERSION"
    s.summary = "Custom RuboCop rules".freeze
    s.authors = ["Developer"].freeze
    s.files = ["lib/rubocop/$CUSTOM_GEM_NAME.rb"].freeze
    s.require_paths = ["lib"].freeze
  end
  EOF
```

  ### Proposed Solutions
  1. Add a configuration option to specify additional gem paths
  2. Allow RuboCop LSP to use bundler from the project directory
  3. Add a hook system for post-installation customization

### Steps to reproduce

  1. Create or have a Ruby project with a custom RuboCop gem/extension
     - For example, a gem called `rubocop-custom` that extends RuboCop with custom rules
     - Located in `your_project/gems/rubocop-custom/lib/rubocop/custom.rb`

  2. Have a `.rubocop.yml` in your project that requires this custom gem:
     ```yaml
     require:
       - rubocop-custom

     # Rest of your RuboCop configuration...

  3. Install RuboCop LSP via Mason in Neovim:
  -- In your Neovim config
  require("mason").setup()
  require("mason-lspconfig").setup({
    ensure_installed = { "rubocop" }
  })
  4. Configure Neovim to use the RuboCop LSP:
  require("lspconfig").rubocop.setup({})
  5. Open a Ruby file in your project


### Affected packages

rubocop

### Neovim version (>= 0.7)

NVIM v0.10.4
Build type: Release
LuaJIT 2.1.1736781742
Run "nvim -V1 -v" for more info

### Operating system/version

Darwin kyle.schwartz 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:23 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6031 x86_64

### Healthcheck

```Text
mason: require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.11.0
- OK PATH: prepend
- OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2025-04-29-crabby-africa` is installed.

mason.nvim [Core utils] ~
- OK unzip: `UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send`
- OK wget: `GNU Wget 1.25.0 built on darwin23.6.0.`
- OK curl: `curl 8.7.1 (x86_64-apple-darwin24.0) libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.63.0`
- OK gzip: `Apple gzip 448.80.1`
- OK gtar: `tar (GNU tar) 1.35`
- OK bash: `GNU bash, version 5.2.26(1)-release (x86_64-apple-darwin23.2.0)`
- OK sh: `Ok`

mason.nvim [Languages] ~
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer failed with exit code - and signal -. composer is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- OK Go: `go version go1.22.6 darwin/amd64`
- OK Ruby: `ruby 3.3.7 (2025-01-15 revision be31f993d7) [x86_64-darwin24]`
- OK node: `v23.9.0`
- WARNING julia: not available
  - ADVICE:
    - spawn: julia failed with exit code - and signal -. julia is not executable
- OK python: `Python 3.13.3`
- OK RubyGem: `3.6.5`
- OK JAVA_HOME: `java version "19.0.1" 2022-10-18`
- OK java: `java version "19.0.1" 2022-10-18`
- OK npm: `10.9.2`
- OK javac: `javac 19.0.1`
- OK pip: `pip 25.0.1 from /usr/local/lib/python3.13/site-packages/pip (python 3.13)`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Wed 30 Apr 01:55:25 2025.
```
